### ISSUE TITLE
Way to limit parsing to currently open CSS file?

### ISSUE THREAD

**Issue by tarasis** [willofindie/vscode-cssvar#29]
Is there a way to limit the parsing so it only looks at the currently open file?

**Comment by phoenisx** [comment]
VSCode already supports local file CSS Variable parsing.
<img width="386" alt="image" src="https://user-images.githubusercontent.com/11786283/160541839-eed3b72e-966e-4079-85d2-68bea5c7c11d.png">

But, I feel you want the features provided by this extension available to Open File Scope.

Let me check if this can be done easily or might take some time.

> Anyhow, I feel this feature should be behind a Config toggle since most users want multiple files to be parsed by default.

**Comment by tarasis** [comment]
Exactly, only parse/show variables for the file I am working on.

I am only learning HTML/CSS/JS and doing mini projects atm, but I use one large dir path of the projects and open the top level in VScode so I can quickly look at other code I've done. (Rather than using multiple windows)

And yeah, definitely behind a config toggle. I'm sure my use case is rarer

```
TopLevel 
  index.html
  style.css
  --FrontendMentor
    --newbie
        --proj1
            index.html
            style.css
        --proj2
            index.html
            style.css
        --proj3
            index.html
            style.css
   --junior
        --proj1
            index.html
            style.css
```

**Comment by phoenisx** [comment]
Will surely look into it. Thanks!

**Comment by lucianahanan** [comment]
I like the idea, it could be also having all of them on the same list, but somehow indicate they are on the current file or are from an external file. Maybe the blue dashes from the popup list having a different color for it, perhaps...

**Comment by phoenisx** [comment]
Hi Folks

This can be achieved using Multi Root workspaces as demonstrated in this [example folder](https://github.com/willofindie/vscode-cssvar/tree/main/examples/multi-root/proj-1), since v1.5.0.

Do keep in mind that VSCode has its own IntelliSense enabled when it comes down to the same CSS file. Thus, you will see duplicate variables in the dropdown list when a variable needs to be accessed.
Every feature from this extension will work as is for a single file. 🎉 

If you keep a single file in different root folders, then this can mimic what you are requesting, which is parsing the currently open file.

**Comment by phoenisx** [comment]
Found that you can disable VSCode's inbuilt CSS variable IntelliSense: https://github.com/willofindie/vscode-cssvar/issues/28#issuecomment-1081555892

**Comment by tarasis** [comment]
Thank you for multi-root support, that works great.

> Found that you can disable VSCode's inbuilt CSS variable IntelliSense: [#28 (comment)](https://github.com/willofindie/vscode-cssvar/issues/28#issuecomment-1081555892)

Sort of, that used to work. Now it disables all variables autocompletes EXCEPT the color variables you provide. I had a few months of not using VS Code so I'm not sure when it broke. I'm currently using VSCode version 1.71.2 and latest version of the extension published 15/09/2022.

Example with `showVariables` set to `false`, it only shows the color variables from your extension

<img width="723" alt="Screenshot 2022-09-16 at 12 04 53" src="https://user-images.githubusercontent.com/3006/190625551-8dbc6384-80f8-4a14-bd4e-e25c531d232c.png">

Example with `showVariables` set to `true`, it shows variables from VS Code and your extension (top --fs-sell from your extension, one below from VS Code)

<img width="758" alt="Screenshot 2022-09-16 at 12 08 57" src="https://user-images.githubusercontent.com/3006/190625972-80076838-02c6-4dd6-b5ee-bda8db055777.png">

Don't know why it partially works setting `showVariables` to `false`, showing just the color variables, but not the rest provided by your extension. Unsure if this is a VSCode bug, or an extension bug.

**Comment by phoenisx** [comment]
There's a conflict with this setting since VSCode v1.70 I guess. I have kept a list of conflicts with VSCode here: https://github.com/willofindie/vscode-cssvar/issues/66


Another user also faced this same issue: https://github.com/willofindie/vscode-cssvar/issues/63#issuecomment-1236347800. The only resolution right now is to disable it, but I couldn't find any way (_yet_) to remove the duplicates in the same file since v1.70.

I will keep you posted if I find any fix.

**Comment by tarasis** [comment]
> There's a conflict with this setting since VSCode v1.70 I guess. I have kept a list of conflicts with VSCode here: #66

Ahh good to know, dang.

> Another user also faced this same issue: [#63 (comment)](https://github.com/willofindie/vscode-cssvar/issues/63#issuecomment-1236347800). The only resolution right now is to disable it, but I couldn't find any way (_yet_) to remove the duplicates in the same file since v1.70.

Gotcha, will do that. At least VSCode's own suggestions consistently come second 

> I will keep you posted if I find any fix.

Cheers 💜

**Comment by lucianahanan** [comment]
I tried to disable with the code added in settings.json, but nothing happened. In the suggestion list I still keep seeing variables from everywhere, not only from the current file.

`"editor.suggest.showVariables": false,`
