### ISSUE TITLE
Does not work on multi root workspaces.

### ISSUE THREAD

**Issue by Esteban-Rocha** [willofindie/vscode-cssvar#32]
Thanks for the EXT. very handy.

That said, I believe it does not work on multi-root workspaces. (@see: [VsCode Multi-root Workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-file-schema) )e.g.:

![image](https://user-images.githubusercontent.com/5914592/163609378-d0a8cd13-bf91-4689-a747-65720555f4e4.png)

To which I tried all the possible combinations and the only way the EXT. does not complain is the following syntax:

`my-project.code-workspace`

```json
{
  "folders": [
    {
      "path": "/rootA"
    },
    {
      "path": "/rootB"
    }
  ],
  "settings": {
    "cssvar.files": {
      "path": "${workspaceFolder}/.../styles/base/pollen/colors.scss"
    }
  }
}
```

This also works on your main `user-settings.json` to remove the notification error popup on vscode. But it still makes the EXT to provide **no intellisense/autocompletions**.

With that explained, I'll love to ask if I may:

- Implement this capability if it is not currently supported as I assume.
- IF` this works but it needs a special config/syntax, could you please **document it**?

Thank you.

Best,

**Comment by phoenisx** [comment]
Thanks, @Esteban-Rocha for opening this issue.

Support for Multi Root workspaces is broken as of now.
I need to revisit the code for a fix 👍🏾

**Comment by Esteban-Rocha** [comment]
Thanks for the heads-up @phoenisx 👍🏻

**Comment by TechnoPvP** [comment]
@phoenisx  Any updates on this really would love to use this with my monorepos?

**Comment by phoenisx** [comment]
Hi @Esteban-Rocha 

Apologies for the delay, was a bit burned out from coding 😅 

Anyways, I have started to work on this again and would love to push this change by 18th Jul. I wanted to know your use cases and how you use this plugin in a Multi Root project.

Please help me answer the following questions to add support for them:
- Do you use this ext in a Mono Repo project, which uses VSCode Multi Root setup? If yes:
  - Do you have a global set of CSS variables that need to be used across every folder in the Multi Root Setup?
  - Do you have different CSS variables for each folder root?

The problem I am trying to solve here is, how to support Multi Root projects for CSS variables because every user can have a different way of setting up their projects.
- Some may want to use locally available CSS variables per folder for each Root in Multi Root setup
- Some may want to use a single set of CSS variables across the entire Multi Root project.

I don't want to make this project complicated and wanted to understand which kind of setup would fit most of the users?
Any ideas?

**Comment by phoenisx** [comment]
Or should I just populate all the CSS variables from each root into a single dropdown across folders, irrespective of which active root a dev is working on?

Just thinking out loud here 🤔 
Would love to get more opinions here

**Comment by phoenisx** [comment]
Hi Folks!!

Multi Root Workspace support has been added to this extension. Apologies for the delay.

Please check [Examples](https://github.com/willofindie/vscode-cssvar/tree/main/examples/multi-root) for reference.

_Also, to keep things simple, each root folder is kept isolated, which means CSS variables present in one root folder won't be accessible in another root folder._

If you need IntelliSense support for CSS variables list from all root folders, please raise a separate ticket 🙇🏾

**Comment by Esteban-Rocha** [comment]
@phoenisx Hey, hope you're doing better, thanks a lot for this, I wasn't able to give you some feedback as I had been a bit busy. But I'll test it for sure, and I think it covers most scenarios.

Thanks again, take care.
