### ISSUE TITLE
[Feat] Support tokencss?

### ISSUE THREAD

**Issue by mayank99** [willofindie/vscode-cssvar#78]
[TokenCSS](https://tokencss.com/) is a brand new tool that statically generates CSS variables from a set of design tokens defined in a `token.config.json` file at the root of the project. It has a postcss plugin that injects those generated custom properties into the css. It would be nice if `vscode-cssvar` could offer autocomplete for these.

**Is your feature request related to a problem? Please describe.**

Tried adding `@tokencss/postcss` to config but it results in "Failed to parse CSS variables" (maybe related to https://github.com/willofindie/vscode-cssvar/issues/52 ?)

<details>

This `tokens.css` file:
```
@inject "tokencss:base";
```

With this `settings.json`:
```
"cssvar.postcssPlugins": ["@tokencss/postcss"]
```

Leads to this error:
```
[cssvar]:  Failed to Parse file (\tokencss-test\src\tokens.css):   :: what ::  TypeError: Invalid host defined options
    at Object.prepare (\tokencss-test\node_modules\@tokencss\postcss\plugin.cjs:6:30)
    at <user>\.vscode\extensions\phoenisx.cssvar-2.3.0\out\extension.js:56:9189
```

</details>

**Comment by phoenisx** [comment]
> `TypeError: Invalid host defined options`

Hi @mayank99 

I've been fiddling with code to support this feature request. The problem is `@tokencss/postcss` does not support `cjs` modules, which fails to get imported into VSCode (Electron) app (Ref: https://github.com/electron/electron/issues/21457).

There's a workaround to this (which I don't want to take) which is to bundle `@tokencss/postcss` in the generated extension.js bundle. This solves the issue, but one significant drawback is maintenance and keeping the extension up-to-date with changes to `@tokencss/postcss`.

I am not sure which path to take to support this plugin 😅 

It would be great if @natemoo-re can separate ESM and CJS bundles, and provide different endpoints for them in `package.json` itself.

**Comment by phoenisx** [comment]
I bundled it only because the plugin was injecting CSS Variables, which is what this extension is built to support.

Anyways, VSCode/Electron will start supporting ESM imports eventually.
In the meantime I will evaluate workarounds (when I have more time) to import ESM.

_Let's hope the former happens sooner 🤞🏽_
