### ISSUE TITLE
[Bug] File associations break cssvar extension

### ISSUE THREAD

**Issue by madeleineostoja** [willofindie/vscode-cssvar#88]
**Describe the bug**
Associating `css` files to `scss` (for nested selectors to work with syntax highlighting when using PostCSS) breaks this extension, it doesn't work at all in css files. Removing the file association fixes it.

**To Reproduce**
1. Add `"files.associations": { "*.css": "scss" }` to user preferences
2. Try use the extension in a css file
3. See error

**Expected behavior**
The extension should work in `.css` files regardless of association, or work in the associated file type (eg: providing `scss` to extensions should work).

**Comment by phoenisx** [comment]
Hi @madeleineostoja 

Thanks for raising the issue!
I am not able to replicate the issue on my end, can you help with the following:

- Which extension version are you facing this issue on. I tried with the latest v2.4.1 and couldn't replicate it.
  - There was a bug in `2.4.0` which got fixed in `2.4.1`.
- Are you using Windows or MacOS?
- Can you also share the error log? Details on how to find the log is mentioned here: https://github.com/willofindie/vscode-cssvar/blob/main/docs/debug-extension.md


https://user-images.githubusercontent.com/11786283/198326325-4ecb092d-6e1e-4e4f-97a3-c24ae0da0192.mp4

**Comment by madeleineostoja** [comment]
Seems to be working now after a hard restart of my system and VS Code. Might have been something to do with upgrading to MacOS Ventura. Sorry for the false alarm!!
