### ISSUE TITLE
Doesn't work with .tsx file

### ISSUE THREAD

**Issue by enyo** [willofindie/vscode-cssvar#9]
Is it normal that this only works with `.css` files? I added this to my settings:

```
{
  "cssvar.files": ["src/components/global-css.tsx"]
}
```

but I don't get any auto complete

**Comment by phoenisx** [comment]
Thanks for using this plugin and supporting it.

This project's main goal is to provide intellisense for CSS variables from CSS like files...

Since JS/TS parsing is very different then CSS, it's not supported yet.

If that's your use-case, as of now this feature is not supported.

Will plan for supporting css variables in JS like files in future.

Will keep this open for the same

**Comment by phoenisx** [comment]
@enyo 

Can u share how you are defining CSS Variables in your TS files?
Since there can be many ways to define CSS Variables in JS-like files, and there's no defined spec to parse CSS variables from JS files, supporting all those scenarios would become out-of-scope for this plugin.

If you are using `postcss` for your project, I would suggest using [CSS envs](https://github.com/csstools/postcss-env-function), as they are part of CSS spec, and I will start supporting CSS `env` in my coming releases. This would make it easier to define and use CSS variables across JS and CSS files.

**Comment by phoenisx** [comment]
@enyo Closing this Issue. Please feel free to open a separate issue if the above comments aren't helpful or the desired solutions for your issue.

**Comment by phoenisx** [comment]
Support for universal parsing will be added as part of #27 , as part of v2.0 release
